### ISSUE TITLE
Throwing NullPointerException when using securityDefinitions with oauth

### ISSUE THREAD

**Issue by jenreh** [RobWin/swagger2markup-gradle-plugin#4]
**yaml:**

```
securityDefinitions:
  basicAuth:
    type: basic
  oauth:
    type: oauth2
    flow: application 
    tokenUrl: "/oauth/token"
```

Throws the following exception. When removing the oauth block eveything ist fine.

**Exception:**

```
Caused by: java.lang.NullPointerException
        at io.github.swagger2markup.internal.document.builder.SecurityDocumentBuilder.buildSecurityScheme(SecurityDocumentBuilder.java:133)
        at io.github.swagger2markup.internal.document.builder.SecurityDocumentBuilder.buildSecuritySchemeDefinitionsSection(SecurityDocumentBuilder.java:97)
        at io.github.swagger2markup.internal.document.builder.SecurityDocumentBuilder.build(SecurityDocumentBuilder.java:78)
        at io.github.swagger2markup.Swagger2MarkupConverter.toFolder(Swagger2MarkupConverter.java:177)
        at io.github.swagger2markup.Swagger2MarkupConverter$toFolder$0.call(Unknown Source)
        at io.github.swagger2markup.tasks.Swagger2MarkupTask.convertSwagger2markup(Swagger2MarkupTask.groovy:68)
        ... 22 more
```

**Comment by jenreh** [comment]
The problem seems to be "type: oauth2"

**Comment by RobWin** [comment]
Hello,

yes. The oauth2 scopes are required and must not be missing.

See: http://swagger.io/specification/#securitySchemeObject

**Comment by jenreh** [comment]
Thank you, changing the yaml to

```
  oauth:
    type: oauth2
    flow: application
    tokenUrl: "/oauth/token"
    scopes:
      write:jarvis: schreibender Zugriff
      read:jarvis: lesender Zugriff
```

helped. A helpfull error message would be nice :-)

**Comment by RobWin** [comment]
Yes, that's correct. Unfortunately I don't have much time atm. Feel free to create a Pull Request. :)

If you use Swagger2Markup, we would love to get your GitHub Star.
